### PR TITLE
Create .gitlab-ci.yml

### PR DESCRIPTION
**Pull request by hhunderter**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# This PR has been tested in the following browsers:

- [ ] Chrome
- [ ] Firefox
- [ ] Opera
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by hhunderter** [comment]
Das wollte ich ausprobieren, da Travis irgendwie nicht mehr Testet / ausgereizt ist.

**Comment by Mairu** [comment]
Ja, allerdings sollten wir dann doch aber eher auf GitHub actions umstellen, da wir GitHub verwenden.

**Comment by hhunderter** [comment]
Aber da frag ich mich wenn Github alles bietet, warum wurde das damals ausgelagert

**Comment by Mairu** [comment]
Als das eingerichtet wurde, gab es GitHub Actions noch nicht.

**Pull request merged**
