### PR TITLE
Add GitHub actions workflow to run tests

### PR DESCRIPTION
**Pull request by Mairu**
# Description

Add a CI GitHub Actions workflow to run tests on pushes and pull requests.

Tests would fail on PHP 8.1 at the moment.

### CODE REVIEW

**Comment by blackcoder87** [comment]
I noticed these warnings:

> Node.js 12 actions are deprecated.
> The `save-state` command is deprecated and will be disabled soon.
> The `set-output` command is deprecated and will be disabled soon.

Is it possible to update the actions as described here or would that break the unit tests?
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by Mairu** [comment]
The save-state issue should be fixed upstream -> https://github.com/shivammathur/setup-php/issues/654

For the Node.js warning, I have not found it in the logs and as we do not actively use it, I guess it will also be fixed upstream.

From my point of view, this is ready to be merged.

Any adjustments like PHP or MySQL versions could be adjusted later.

**Comment by Mairu** [comment]
Well the php unit version question should be answered, and for sure the version from the vendor folder has to be used. So if you change the tests for whatever PHPUnit version, you have to adjust the version in the composer.json file. @hhunderter

**Comment by blackcoder87** [comment]
So my fix for the unit test should be merged and then this pull request. After that the unit tests should be fine for PHP 7.4 and PHP 8.0 with PHPUnit 5.7.27.
Later the tests should be run for PHP 7.0 - PHP 8.1 as long as Ilch supports the older versions of PHP. 

See this comment:
https://github.com/IlchCMS/Ilch-2.0/pull/588#issuecomment-1320823078

**Pull request merged**
