### PR TITLE
Build pipeline

### LINKED ISSUE #592: Trigger build script with GitHub Actions
**Is your feature request related to a problem? Please describe.**
The newest state of development version for users is out of date as the build script no longer runs with changes to the master.
Further it was comfortable to use the result of the build script for actual releases. The build script was trigger when creating a release/tag. This was previously done with Travis.

**Describe the solution you'd like**
Trigger the build script with GitHub Actions when the master changes and/or a release/tag is created. Try to replicate the behavior it had when Travis triggered it, please.

**Additional context**
https://github.com/IlchCMS/Ilch-2.0/blob/v2.1.43/.travis.yml#L28
https://github.com/IlchCMS/Ilch-2.0/tree/master/build

### PR DESCRIPTION
**Pull request by Mairu**
# Description

* add GitHub action
  * that creates a Ilch2 archive (on the master branch, should be possible to trigger manually for other branches)
    * There is a limitation when downloading the archive from GitHub actions page, that it is inside a zip folder -> https://github.com/actions/upload-artifact#zipped-artifact-downloads
    * also artifacts will be deleted after 90 days
  * create a release draft when a tag in the form v1.2.3 or v1.2.3-alpha-1 is created
    * archive is attached to that release draft -> example: https://github.com/IlchCMS/Ilch-2.0/releases/tag/untagged-3ed336c0f196dc4998e1

Closes #592

### CODE REVIEW

**Comment by blackcoder87** [comment]
The deletion of artifacts? doesn't seem like a problem to me as we would attach the build for a release to the actual news anyway and older builds of the development states of the past are of limited interest.

Nice work. Thanks. :)

**Comment by blackcoder87** [comment]
Is it possible to add a URL to the latest build here?
https://github.com/IlchCMS/Ilch-2.0/blob/master/README.md?plain=1#L8

**Comment by Mairu** [comment]
I don't think so, because the runs have ids, but we could upload the archive to the ilch.de server.

**Comment by blackcoder87** [comment]
Looks like there is really no simple solution like with the latest release link [1] so far:

https://github.com/actions/upload-artifact/issues/21
https://stackoverflow.com/questions/60789862/url-of-the-last-artifact-of-a-github-action-build

We should remove the outdated link in the readme.md if we don't decide to upload the latest artifact to the ilch.de server.

The one I can download here, looks like it is a zip in a zip file:
https://github.com/IlchCMS/Ilch-2.0/actions/runs/3553008062

Other than that it looks good to me as the result looks fine and could be used for a release.

[1] https://github.com/IlchCMS/Ilch-2.0/releases/latest

**Comment by Mairu** [comment]
I have added the sftp upload.

**Comment by blackcoder87** [comment]
I assume this needs to be merged to see the actual result?

http://www.ilch.de/ilch2/versions/master.zip
Looks like this is still old (quick check of the index.php) or is the URL different?

Did you notice that the zip file is zipped again?
https://github.com/IlchCMS/Ilch-2.0/suites/9516087974/artifacts/451827331

Thanks for the work. This would already greatly ease the release of a new ilch version.

**Comment by Mairu** [comment]
Mhh, well the upload already happed, but I forgot to pull before creating the build-pipeline branch, so it is based on https://github.com/IlchCMS/Ilch-2.0/commit/400c49efb1a2f86569e42a3e8e43efea38337eb0.

But yes on merge it should run again and build the newest version.

-----------------

> Did you notice that the zip file is zipped again?
https://github.com/IlchCMS/Ilch-2.0/suites/9516087974/artifacts/451827331

Yes, that is what I meant with
> There is a limitation when downloading the archive from GitHub actions page, that it is inside a zip folder -> https://github.com/actions/upload-artifact#zipped-artifact-downloads

Should have written file instead of folder though.

**Comment by blackcoder87** [comment]
Ah ok, no problem then.

LGTM.

**Pull request merged**
